"""
Constrained GenAI service wrapper
"""

from __future__ import annotations

import logging
from typing import Callable, Dict, Any, List, Optional

from .schema import GenAIMealText


logger = logging.getLogger(__name__)


class GenAIService:
    """Schema-enforced GenAI helper"""

    def __init__(self, generator: Callable[[Dict[str, Any]], Dict[str, Any]]) -> None:
        self._generator = generator

    async def generate_meal_text(
        self,
        ingredients: List[Dict[str, Any]],
        meal_type: str,
        diet_type: Any,
        allergies: Optional[List[str]] = None,
        foods_to_avoid: Optional[List[str]] = None,
        budget_constraints: Optional[str] = None,
        lifestyle_constraints: Optional[str] = None
    ) -> Dict[str, Any]:
        payload = {
            "ingredients": ingredients,
            "meal_type": meal_type,
            "diet_type": diet_type,
            "allergies": allergies or [],
            "foods_to_avoid": foods_to_avoid or [],
            "budget_constraints": budget_constraints,
            "lifestyle_constraints": lifestyle_constraints
        }
        raw = await self._generator(payload)
        try:
            validated = GenAIMealText.model_validate(raw)
            logger.info("[GENAI_SCHEMA_VALID]")
            return {
                "meal_name": validated.meal_name,
                "description": validated.description,
                "steps": validated.steps,
                "prep_time_minutes": validated.prep_time_minutes,
                "cook_time_minutes": validated.cook_time_minutes,
                "servings": validated.servings
            }
        except Exception:
            logger.warning("[GENAI_SCHEMA_INVALID_FALLBACK]")
            fallback_name = f"{meal_type.capitalize()} with {ingredients[0]['name']}" if ingredients else "Meal"
            return {
                "meal_name": fallback_name,
                "description": "A nutritious meal generated by our ML pipeline.",
                "steps": ["Prepare ingredients", "Assemble meal"],
                "prep_time_minutes": 10,
                "cook_time_minutes": 20,
                "servings": 1
            }

    def generate_daily_plan_text(
        self,
        meals: List[Dict[str, Any]],
        diet_type: str = "vegetarian",
        **kwargs
    ) -> Dict[str, Any]:
        """Generate summary and notes for a daily plan."""
        calories = sum(m.get("nutrition", {}).get("calories", 0) for m in meals)
        protein = sum(m.get("nutrition", {}).get("protein", 0) for m in meals)
        
        return {
            "summary": f"A balanced daily plan with {len(meals)} meals, totaling {calories:.0f} calories and {protein:.1f}g protein.",
            "notes": "Drink plenty of water and stay active!"
        }

    async def generate_protein_supplement_note(
        self,
        missing_protein_g: float,
        diet_type: str,
        allergies: Optional[List[str]] = None,
        nutrition_targets: Optional[Dict[str, Any]] = None,
        safety_constraints: Optional[Dict[str, Any]] = None
    ) -> str:
        payload = {
            "action": "generate_supplement_note",
            "missing_protein_g": missing_protein_g,
            "diet_type": diet_type,
            "allergies": allergies or [],
            "nutrition_targets": nutrition_targets or {},
            "safety_constraints": safety_constraints or {}
        }
        raw = await self._generator(payload)
        if raw and isinstance(raw, dict) and "note" in raw:
            return raw["note"]
        return f"Note: To meet your rigorous protein target, consider adding a protein supplement to cover your {missing_protein_g:.1f}g deficit."
