"""
Constrained GenAI service wrapper
"""

from __future__ import annotations

import logging
from typing import Callable, Dict, Any, List

from .schema import GenAIMealText


logger = logging.getLogger(__name__)


class GenAIService:
    """Schema-enforced GenAI helper"""

    def __init__(self, generator: Callable[[Dict[str, Any]], Dict[str, Any]]) -> None:
        self._generator = generator

    def generate_meal_text(
        self,
        ingredients: List[Dict[str, Any]],
        meal_type: str,
        diet_type: Any
    ) -> Dict[str, Any]:
        payload = {
            "ingredients": ingredients,
            "meal_type": meal_type,
            "diet_type": diet_type
        }
        raw = self._generator(payload)
        try:
            validated = GenAIMealText.model_validate(raw)
            logger.info("[GENAI_SCHEMA_VALID]")
            return {
                "name": validated.meal_name,
                "description": validated.description,
                "instructions": "\n".join(validated.steps),
                "prep_time": validated.prep_time_minutes,
                "cook_time": validated.cook_time_minutes
            }
        except Exception:
            logger.warning("[GENAI_SCHEMA_INVALID_FALLBACK]")
            fallback_name = f"{meal_type.capitalize()} with {ingredients[0]['name']}" if ingredients else "Meal"
            return {
                "name": fallback_name,
                "description": "A nutritious meal generated by our ML pipeline.",
                "instructions": "Prepare ingredients and assemble meal.",
                "prep_time": 10,
                "cook_time": 20
            }

    def generate_daily_plan_text(
        self,
        meals: List[Dict[str, Any]],
        diet_type: str = "vegetarian",
        **kwargs
    ) -> Dict[str, Any]:
        """Generate summary and notes for a daily plan."""
        calories = sum(m.get("nutrition", {}).get("calories", 0) for m in meals)
        protein = sum(m.get("nutrition", {}).get("protein", 0) for m in meals)
        
        return {
            "summary": f"A balanced daily plan with {len(meals)} meals, totaling {calories:.0f} calories and {protein:.1f}g protein.",
            "notes": "Drink plenty of water and stay active!"
        }
