"""add api_verified to food_items

Revision ID: 0e45c4a77a96
Revises: e0d8388f688a
Create Date: 2026-04-18 02:31:03.530352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e45c4a77a96'
down_revision: Union[str, None] = 'e0d8388f688a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_diet_plans_created_at', table_name='diet_plans')
    op.drop_index('ix_diet_plans_hcd_id', table_name='diet_plans')
    op.drop_index('ix_diet_plans_user_id', table_name='diet_plans')
    op.drop_index('ix_diet_preferences_user_id', table_name='diet_preferences')
    op.add_column('food_items', sa.Column('api_verified', sa.Boolean(), server_default='false', nullable=False))
    op.drop_index('ix_health_context_documents_is_active', table_name='health_context_documents')
    op.drop_index('ix_health_context_documents_user_id', table_name='health_context_documents')
    op.drop_index('ix_health_goals_user_id', table_name='health_goals')
    op.drop_constraint('uq_registration_requests_email', 'registration_requests', type_='unique')
    op.drop_index('ix_registration_requests_email', table_name='registration_requests')
    op.create_index(op.f('ix_registration_requests_email'), 'registration_requests', ['email'], unique=True)
    op.drop_index('ix_users_created_at', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.drop_index(op.f('ix_registration_requests_email'), table_name='registration_requests')
    op.create_index('ix_registration_requests_email', 'registration_requests', ['email'], unique=False)
    op.create_unique_constraint('uq_registration_requests_email', 'registration_requests', ['email'])
    op.create_index('ix_health_goals_user_id', 'health_goals', ['user_id'], unique=False)
    op.create_index('ix_health_context_documents_user_id', 'health_context_documents', ['user_id'], unique=False)
    op.create_index('ix_health_context_documents_is_active', 'health_context_documents', ['is_active'], unique=False)
    op.drop_column('food_items', 'api_verified')
    op.create_index('ix_diet_preferences_user_id', 'diet_preferences', ['user_id'], unique=False)
    op.create_index('ix_diet_plans_user_id', 'diet_plans', ['user_id'], unique=False)
    op.create_index('ix_diet_plans_hcd_id', 'diet_plans', ['hcd_id'], unique=False)
    op.create_index('ix_diet_plans_created_at', 'diet_plans', ['created_at'], unique=False)
    # ### end Alembic commands ###
