"""add_history_tables_for_chats_and_messages

Revision ID: 18839adc0a64
Revises: add_food_embeddings_table
Create Date: 2026-03-15 01:23:01.508202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18839adc0a64'
down_revision: Union[str, None] = 'add_food_embeddings_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_diet_plans_created_at', table_name='diet_plans')
    op.drop_index('ix_diet_plans_hcd_id', table_name='diet_plans')
    op.drop_index('ix_diet_plans_user_id', table_name='diet_plans')
    op.add_column('diet_preferences', sa.Column('cuisine', sa.String(length=50), nullable=False, server_default='indian'))
    op.add_column('diet_preferences', sa.Column('reuse_ingredients', sa.Boolean(), nullable=False, server_default='false'))
    op.drop_index('ix_diet_preferences_user_id', table_name='diet_preferences')
    op.drop_index('ix_health_context_documents_is_active', table_name='health_context_documents')
    op.drop_index('ix_health_context_documents_user_id', table_name='health_context_documents')
    op.drop_index('ix_health_goals_user_id', table_name='health_goals')
    op.drop_constraint('uq_registration_requests_email', 'registration_requests', type_='unique')
    op.drop_index('ix_registration_requests_email', table_name='registration_requests')
    op.create_index(op.f('ix_registration_requests_email'), 'registration_requests', ['email'], unique=True)
    op.drop_index('ix_users_created_at', table_name='users')
    
    # Create chats table
    op.create_table('chats',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_user_id'), 'chats', ['user_id'], unique=False)

    # Create messages table
    op.create_table('messages',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('chat_id', sa.UUID(), nullable=False),
        sa.Column('role', sa.String(length=50), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('metadata_json', sa.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.drop_index(op.f('ix_registration_requests_email'), table_name='registration_requests')
    op.create_index('ix_registration_requests_email', 'registration_requests', ['email'], unique=False)
    op.create_unique_constraint('uq_registration_requests_email', 'registration_requests', ['email'])
    op.create_index('ix_health_goals_user_id', 'health_goals', ['user_id'], unique=False)
    op.create_index('ix_health_context_documents_user_id', 'health_context_documents', ['user_id'], unique=False)
    op.create_index('ix_health_context_documents_is_active', 'health_context_documents', ['is_active'], unique=False)
    op.create_index('ix_diet_preferences_user_id', 'diet_preferences', ['user_id'], unique=False)
    op.drop_column('diet_preferences', 'reuse_ingredients')
    op.drop_column('diet_preferences', 'cuisine')
    op.create_index('ix_diet_plans_user_id', 'diet_plans', ['user_id'], unique=False)
    op.create_index('ix_diet_plans_hcd_id', 'diet_plans', ['hcd_id'], unique=False)
    op.create_index('ix_diet_plans_created_at', 'diet_plans', ['created_at'], unique=False)
    
    # Drop chats and messages
    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_chats_user_id'), table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
