"""create v2 meal engine tables

Revision ID: 55cdac51ef9f
Revises: drop_orphaned_tables
Create Date: 2026-04-18 21:30:09.259402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '55cdac51ef9f'
down_revision: Union[str, None] = 'drop_orphaned_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('v2_external_nutrition_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_key', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_key')
    )
    op.create_table('v2_pairing_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cuisine', sa.String(length=50), nullable=False),
    sa.Column('item', sa.String(length=100), nullable=False),
    sa.Column('preferred', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('acceptable', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('incompatible', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuisine', 'item', name='uq_v2_pairing_rules_cuisine_item')
    )
    op.create_table('v2_regions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('v2_ingredients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scientific_name', sa.String(length=255), nullable=True),
    sa.Column('food_group', sa.String(length=100), nullable=False),
    sa.Column('region_code', sa.Integer(), nullable=True),
    sa.Column('regional_names', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('search_aliases', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('diet_tags', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('form', sa.String(length=20), server_default='unspecified', nullable=False),
    sa.Column('kcal', sa.Float(), nullable=False),
    sa.Column('enerc_kj', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fiber_g', sa.Float(), nullable=False),
    sa.Column('sugar_g', sa.Float(), nullable=True),
    sa.Column('starch_g', sa.Float(), nullable=True),
    sa.Column('sat_fat_g', sa.Float(), nullable=True),
    sa.Column('mufa_g', sa.Float(), nullable=True),
    sa.Column('pufa_g', sa.Float(), nullable=True),
    sa.Column('trans_fat_g', sa.Float(), nullable=True),
    sa.Column('omega3_g', sa.Float(), nullable=True),
    sa.Column('omega6_g', sa.Float(), nullable=True),
    sa.Column('cholesterol_mg', sa.Float(), nullable=True),
    sa.Column('calcium_mg', sa.Float(), nullable=True),
    sa.Column('iron_mg', sa.Float(), nullable=True),
    sa.Column('magnesium_mg', sa.Float(), nullable=True),
    sa.Column('zinc_mg', sa.Float(), nullable=True),
    sa.Column('sodium_mg', sa.Float(), nullable=True),
    sa.Column('potassium_mg', sa.Float(), nullable=True),
    sa.Column('phosphorus_mg', sa.Float(), nullable=True),
    sa.Column('vit_a_mcg', sa.Float(), nullable=True),
    sa.Column('vit_c_mg', sa.Float(), nullable=True),
    sa.Column('vit_d_mcg', sa.Float(), nullable=True),
    sa.Column('vit_b_mg', sa.Float(), nullable=True),
    sa.Column('vit_e_mg', sa.Float(), nullable=True),
    sa.Column('folate_mcg', sa.Float(), nullable=True),
    sa.Column('water_g', sa.Float(), nullable=True),
    sa.Column('ash_g', sa.Float(), nullable=True),
    sa.Column('raw_ifct_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('nutrient_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_quality', sa.String(length=50), nullable=True),
    sa.Column('data_source', sa.String(length=50), server_default='ifct_2017', nullable=False),
    sa.Column('confidence', sa.String(length=20), server_default='verified', nullable=False),
    sa.Column('app_serving_units', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meal_archetype_roles', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('custom_aliases', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("form IN ('raw', 'cooked', 'unspecified')", name='check_v2_ingredients_form'),
    sa.ForeignKeyConstraint(['region_code'], ['v2_regions.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_v2_ingredients_diet_tags', 'v2_ingredients', ['diet_tags'], unique=False, postgresql_using='gin')
    op.create_index('ix_v2_ingredients_food_group', 'v2_ingredients', ['food_group'], unique=False)
    op.create_index('ix_v2_ingredients_form', 'v2_ingredients', ['form'], unique=False)
    op.create_index('ix_v2_ingredients_search_aliases', 'v2_ingredients', ['search_aliases'], unique=False, postgresql_using='gin')
    # Enable pgvector extension for embedding storage
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table('v2_ingredient_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('embedding', Vector(384), nullable=False),
    sa.Column('text_used', sa.String(length=500), nullable=False),
    sa.Column('model_name', sa.String(length=100), server_default='all-MiniLM-L6-v2', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['v2_ingredients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredient_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('v2_ingredient_embeddings')
    op.drop_index('ix_v2_ingredients_search_aliases', table_name='v2_ingredients', postgresql_using='gin')
    op.drop_index('ix_v2_ingredients_form', table_name='v2_ingredients')
    op.drop_index('ix_v2_ingredients_food_group', table_name='v2_ingredients')
    op.drop_index('ix_v2_ingredients_diet_tags', table_name='v2_ingredients', postgresql_using='gin')
    op.drop_table('v2_ingredients')
    op.drop_table('v2_regions')
    op.drop_table('v2_pairing_rules')
    op.drop_table('v2_external_nutrition_cache')
    # ### end Alembic commands ###
