"""add engine_version to diet_plans

Revision ID: dcacec4d1096
Revises: 07f0d3c8039d
Create Date: 2026-04-19 02:16:06.923293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcacec4d1096'
down_revision: Union[str, None] = '07f0d3c8039d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diet_plans', sa.Column('engine_version', sa.String(length=10), server_default='v1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diet_plans', 'engine_version')
    # ### end Alembic commands ###
